name: Auto Version

on:
  push:
    branches: [master, staging]

jobs:
  version:
    runs-on: web-default
    if: >-
      ${{ !contains(github.event.head_commit.message, '[skip ci]') &&
          !contains(github.event.head_commit.message, '[ci skip]') }}
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Auto Version
        uses: ./
        with:
          version-file: VERSION
          github-token: ${{ secrets.GITHUB_TOKEN }}
          github-api-url: ${{ github.api_url }}
          update-floating-tags: "true"
